const menu = [
  {
    id: 1,
    title: "La Phe Tot",
    category: "appetizer",
    price: 9.99,
    img: "./images/item-1.jpg",
    desc: `Seasoned tea leaves mixed with shrerdded cabbages, tomatoes, fresh garlic topped with chief special dressing, ground seasoned seed, peanuts and fried broad beans `,
  },
  {
    id: 2,
    title: "A Kyaw Sone",
    category: "appetizer",
    price: 9.99,
    img: "./images/item-2.jpg",
    desc: `Seasoned tea leaves mixed with shrerdded cabbages, tomatoes, fresh garlic topped with chief special dressing, ground seasoned seed, peanuts and fried broad beans `,
  },
  {
    id: 3,
    title: "Deep Fried Togu",
    category: "appetizer",
    price: 8.99,
    img: "./images/item-3.jpg",
    desc: `Based on popular demand this is a dish of deep fried tofu served with homemade Burmese dipping sauce.`,
  },
  {
    id: 4,
    title: "Somosa",
    category: "appetizer",
    price: 5.99,
    img: "./images/item-4.jpg",
    desc: `Deep fried parcel of soft potatoes, onion green peas seasoned with light curry and spices. Served with homemade dipping sauce 4 pcs per serving`,
  },
  {
    id: 5,
    title: "Buu Tee Kyaw(aka) Deep fried Courd",
    category: "appetizer",
    price: 8.99,
    img: "./images/item-5.jpg",
    desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
  },
  {
    id: 6,
    title: "Palata",
    category: "appetizer",
    price: 2.99,
    img: "./images/item-5.jpg",
    desc: `FHouse made layered bread(2 slices), served with our famous curry sauce  `,
  },
  {
    id: 7,
    title: "Ei Kyar Kway",
    category: "appetizer",
    price: 2.5,
    img: "./images/item-5.jpg",
    desc: `Burmese style French bread`,
  },
  {
    id: 7,
    title: "Moh let Kout - Burmese Donut",
    category: "appetizer",
    price: 2.5,
    img: "./images/item-5.jpg",
    desc: `Deep fried glutinous flour served with syrup or powdered sugar, 5 pieces 
    `,
  },
];
export default menu;
