// const menu = [
//   {
//     id: 1,
//     title: "La Phe Tot",
//     category: "appetizer",
//     price: 9.99,
//     img: "./images/item-1.jpg",
//     desc: `Seasoned tea leaves mixed with shrerdded cabbages, tomatoes, fresh garlic topped with chief special dressing, ground seasoned seed, peanuts and fried broad beans `,
//   },
//   {
//     id: 2,
//     title: "A Kyaw Sone",
//     category: "entree",
//     price: 9.99,
//     img: "./images/item-2.jpg",
//     desc: `Seasoned tea leaves mixed with shrerdded cabbages, tomatoes, fresh garlic topped with chief special dressing, ground seasoned seed, peanuts and fried broad beans `,
//   },
//   {
//     id: 3,
//     title: "Samosa",
//     category: "drinks",
//     price: 6.99,
//     img: "./images/item-3.jpg",
//     desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
//   },
//   {
//     id: 4,
//     title: "A Kyaw Zone",
//     category: "appetizer",
//     price: 20.99,
//     img: "./images/item-4.jpg",
//     desc: `This is a tempura dish with deep fried Burmese tofu, deep fried Burmese rice cake with black bean, garlic and ginger seasoning and deep fried Burmese rice caked with sweet peans and seasoning mixed inside`,
//   },
//   {
//     id: 5,
//     title: "egg attack",
//     category: "entree",
//     price: 22.99,
//     img: "./images/item-5.jpg",
//     desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
//   },
//   {
//     id: 6,
//     title: "oreo dream",
//     category: "drinks",
//     price: 18.99,
//     img: "./images/item-6.jpg",
//     desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
//   },
//   {
//     id: 7,
//     title: "bacon overflow",
//     category: "appetizer",
//     price: 8.99,
//     img: "./images/item-7.jpg",
//     desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
//   },
//   {
//     id: 8,
//     title: "american classic",
//     category: "entree",
//     price: 12.99,
//     img: "./images/item-8.jpg",
//     desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
//   },
//   {
//     id: 9,
//     title: "quarantine buddy",
//     category: "drinks",
//     price: 16.99,
//     img: "./images/item-9.jpg",
//     desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
//   },
// ];
// export default menu;

const menu = [
  {
    id: 1,
    title: "M-1. Kyi Oo, Recommended",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-1.jpeg",
    desc: `Thin riced noodle soup in pork broth. The bowl comes with minced pork, pork meatball, sliced pork, fishball, fish cakes, tofu, mustard green and green onion. Seasoned with spices and black pepper. Served with soy sauce a d hot chillies dipping sauce`,
  },
  {
    id: 2,
    title: "M-2. Myi Oo Mee Shii, Recommended",
    category: "entree",
    price: 10.99,
    img: "./images/entree/e-2.jpeg",
    desc: `Noodle soup served in a clay pot with seafood, fish balls, fish cakes, mixed vegetable, poached egg, topped with cilantro, green onion and ground sesame seeds with black pepper seasoning. A little bit spicy. Your choice of chicken or pork 
      broth and Udon or rice flat noodle
      `,
  },
  {
    id: 3,
    title: "M-3 Shan Noodle",
    category: "entree",
    price: 8.99,
    img: "./images/entree/e-3.jpeg",
    desc: `Noodle mixed with chicken, ground peanuts and sesame seeds, green onion and topped with a homemade dressing. A little bit spicy. Served with homemade pickled 
      mustard green and a cup of broth.`,
  },
  //to be continued
  {
    id: 4,
    title: "M-4 Tom Yum Noddle Soup",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-4.jpeg",
    desc: `Our chef special Burmese hot and sour noodle soup with seafood and Enoki mushroom (the long thin stalk white mushroom). Your choice of rice noodle or egg 
      noodle`,
  },
  {
    id: 5,
    title: "M-5 Tofu Tot",
    category: "entree",
    price: 8.99,
    img: "./images/entree/e-5.jpeg",
    desc: `Burmese tofu salad mixed with cilantro, shredded cabbage, green onion, topped 
      with chef special dressing, ground peanut and sesame seed`,
  },
  {
    id: 6,
    title: "M-6 Kyi OO Sichat",
    category: "entree",
    price: 10.99,
    img: "./images/entree/e-6.jpeg",
    desc: `Seasoned rice noodle served with a bowl of broth with mince pork, pork meatball, 
      fishball, fishcakes, mustard green and green onion 
       `,
  },
  {
    id: 7,
    title: "M-7 Nan Gyi/Nan Tay",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-7.jpeg",
    desc: `Stir fry marinated chicken with cabbage and cilantro. Seasoned with spices and roasted soy bean powder. Mixed with your choice of Udon or thin rice noodle. 
      Served with a cup of broth on the side. `,
  },
  {
    id: 8,
    title: "M-8 Pork Curry",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-8.jpeg",
    desc: `Pork belly stew in our famous chef special Burmese curry. Served with steamed rice .`,
  },
  {
    id: 9,
    title: "M-9 Beef Curry",
    category: "entree",
    price: 12.99,
    img: "./images/entree/e-9.jpeg",
    desc: `Beef stew in our famous chef special Burmese curry.. Served with steamed rice.`,
  },
  {
    id: 10,
    title: "Chicken Rice(Tuesdays)",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-10.jpeg",
    desc: `Deep fried seasoned chicken shredded, served with rice steamed in chicken broth 
      and homemade hot and sour dipping sauce.`,
  },
  {
    id: 11,
    title: "M-11 Moh Hin Khaa, Recommended(Thursday to Sunday)",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-11.jpeg",
    desc: `FThis dish involves fine craft. Fish is seasoned, cooked and blended into a thick and flavorful soup, combined with Burmese seasoning, yellow split peas, hard-boiled 
      egg, cilantro and rice noodle. A lime wedge is served at your choosing `,
  },
  {
    id: 12,
    title: "M-12 La Phet Tha Min (Vegetarian)",
    category: "entree",
    price: 8.99,
    img: "./images/entree/e-12.jpeg",
    desc: `Steam rice mixed with seasoned tea leaves, special dressing and an over-medium 
      `,
  },
  {
    id: 13,
    title: "M-13 A Tot Sone",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-13.jpeg",
    desc: `Tofu, chicken with udon and rice noodle . `,
  },
  {
    id: 14,
    title: "M-14 Bak Kut The",
    category: "entree",
    price: 12.99,
    img: "./images/entree/e-14.jpeg",
    desc: `Pork ribs, belly, enoki mushroom, spinach, green onion soup prepared for hours 
      `,
  },
  {
    id: 15,
    title: "M-15 Chef Special Fried Rice",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-15.jpeg",
    desc: `Fragrant rice fried with shrimp, mixed veggies and special seasoning`,
  },
  {
    id: 16,
    title: "M-16 Laksa",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-16.jpeg",
    desc: `Coconut curry noodle soup with shrimp, fishcakes, tofu, green onion, beansprouts 
    and cilantro.`,
  },
  {
    id: 17,
    title: "M-17 Thamin Tot",
    category: "entree",
    price: 7.99,
    img: "./images/entree/e-17.jpeg",
    desc: `Mixed rice with seasoned chicken. Topped with a fried egg`,
  },
  {
    id: 18,
    title: "M-18 Rakhine Mohtii",
    category: "entree",
    price: 9.99,
    img: "./images/entree/e-18.jpeg",
    desc: `Deep fried fish filet slightly crushed and mixed with rice noodle and house made 
    hot and sour dressing. It is spicy! 
    `,
  },
  {
    id: 19,
    title: "M-19 Papaya Salad(Burmese Style)",
    category: "entree",
    price: 7.99,
    img: "./images/entree/e-19.jpeg",
    desc: `Shredded green papaya, fresh Burmese tofu, cabbage, cilantro mixed with our unique salad dressing sprinkled with roasted sesame and ground peanuts 
    `,
  },
  {
    id: 20,
    title: "La Phe Tot",
    category: "appetizer",
    price: 9.99,
    img: "./images/appetizer/a-1.jpeg",
    desc: `Seasoned tea leaves mixed with shrerdded cabbages, tomatoes, fresh garlic topped with chief special dressing, ground seasoned seed, peanuts and fried broad beans `,
  },
  {
    id: 21,
    title: "A Kyaw Sone",
    category: "appetizer",
    price: 9.99,
    img: "./images/appetizer/a-2.jpeg",
    desc: `Seasoned tea leaves mixed with shrerdded cabbages, tomatoes, fresh garlic topped with chief special dressing, ground seasoned seed, peanuts and fried broad beans `,
  },
  {
    id: 22,
    title: "Deep Fried Togu",
    category: "appetizer",
    price: 8.99,
    img: "./images/appetizer/a-3.jpeg",
    desc: `Based on popular demand this is a dish of deep fried tofu served with homemade Burmese dipping sauce.`,
  },
  {
    id: 23,
    title: "Somosa",
    category: "appetizer",
    price: 5.99,
    img: "./images/appetizer/a-4.jpeg",
    desc: `Deep fried parcel of soft potatoes, onion green peas seasoned with light curry and spices. Served with homemade dipping sauce 4 pcs per serving`,
  },
  {
    id: 24,
    title: "Buu Tee Kyaw(aka) Deep fried Courd",
    category: "appetizer",
    price: 8.99,
    img: "./images/appetizer/a-5.jpeg",
    desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
  },
  {
    id: 25,
    title: "Palata",
    category: "appetizer",
    price: 2.99,
    img: "./images/appetizer/a-6.jpeg",
    desc: `FHouse made layered bread(2 slices), served with our famous curry sauce  `,
  },
  {
    id: 26,
    title: "Ei Kyar Kway",
    category: "appetizer",
    price: 2.5,
    img: "./images/appetizer/a-7.jpeg",
    desc: `Burmese style French bread, Burmese style French bread `,
  },
  {
    id: 27,
    title: "Moh let Kout - Burmese Donut",
    category: "appetizer",
    price: 2.5,
    img: "./images/appetizer/a-8.jpeg",
    desc: `Deep fried glutinous flour served with syrup or powdered sugar, 5 pieces 
    `,
  },
  {
    id: 28,
    title: "Coffee",
    category: "drinks",
    price: 9.99,
    img: "./images/drinks/d-1.jpeg",
    desc: `FHouse made layered bread(2 slices), served with our famous curry sauce  `,
  },
  {
    id: 29,
    title: "Milk Tea",
    category: "drinks",
    price: 2.5,
    img: "./images/drinks/d-2.jpeg",
    desc: `FHouse made layered bread(2 slices), served with our famous curry sauce  `,
  },
  {
    id: 30,
    title: "Hot Green Tea",
    category: "drinks",
    price: 3.5,
    img: "./images/drinks/d-3.jpeg",
    desc: `FHouse made layered bread(2 slices), served with our famous curry sauce  `,
  },
  {
    id: 31,
    title: "Pepsi",
    category: "drinks",
    price: 2.6,
    img: "./images/drinks/d-4.jpeg",
    desc: `FHouse made layered bread(2 slices), served with our famous curry sauce  `,
  },
  {
    id: 32,
    title: "Soda",
    category: "drinks",
    price: 2.6,
    img: "./images/drinks/d-5.jpeg",
    desc: `FHouse made layered bread(2 slices), served with our famous curry sauce  `,
  },
  {
    id: 33,
    title: "Iced Milk Tea",
    category: "drinks",
    price: 2.99,
    img: "./images/drinks/d-6.webp",
    desc: `FHouse made layered bread(2 slices), served with our famous curry sauce  `,
  },
  {
    id: 34,
    title: "iced Coffee",
    category: "drinks",
    price: 2.99,
    img: "./images/drinks/d-7.jpeg",
    desc: `House made layered bread(2 slices), served with our famous curry sauce  `,
  },
];
export default menu;
