const menu = [
    {
      id: 1,
      title: 'M-1. Kyi Oo',
      category: 'entree',
      price: 9.99,
      img: './images/item-1.jpg',
      desc: `Thin riced noodle soup in pork broth. The bowl comes with minced pork, pork meatball, sliced pork, fishball, fish cakes, tofu, mustard green and green onion. Seasoned with spices and black pepper. Served with soy sauce a d hot chillies dipping sauce`,
    }
    {
      id: 2,
      title: 'M-2. Myi Oo Mee Shii',
      category: 'entree',
      price: 10.99,
      img: './images/item-2.jpg',
      desc: `Noodle soup served in a clay pot with seafood fish balss, fish cakes, mixed vegatables, posched eggs, topped with cilantro, green onion and gournd sesame seeds with black pepper seasoning, Alittl bit spicy. Your choice of chicken or pork broth and Udon or rice noodle`,

    },
    {
      id: 3,
      title: 'M-3 Shan Noodle',
      category: 'entree',
      price: 8.99,
      img: './images/item-3.jpg',
      desc: `Noodle mixed with chikcen, ground peanuts and seasme seed, green onion and topped with a lemondae dressing. A little bit spicy. Served with homemade pickled mustard green and a cup of broth.`,
    },
    //to be continued
    {
      id: 4,
      title: 'Somosa',
      category: 'entree',
      price: 5.99,
      img: './images/item-4.jpg',
      desc: `Deep fried parcel of soft potatoes, onion green peas seasoned with light curry and spices. Served with homemade dipping sauce 4 pcs per serving`,
       
    },
    {
      id: 5,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 6,
      title: 'La Phe Tot',
      category: 'entree',
      price: 9.99,
      img: './images/item-1.jpg',
      desc: `Seasoned tea leaves mixed with shrerdded cabbages, tomatoes, fresh garlic topped with chief special dressing, ground seasoned seed, peanuts and fried broad beans `,
    },
    {
      id: 7,
      title: 'A Kyaw Sone',
      category: 'entree',
      price: 9.99,
      img: './images/item-2.jpg',
      desc: `Seasoned tea leaves mixed with shrerdded cabbages, tomatoes, fresh garlic topped with chief special dressing, ground seasoned seed, peanuts and fried broad beans `,

    },
    {
      id: 8,
      title: 'Deep Fried Togu',
      category: 'entree',
      price: 8.99,
      img: './images/item-3.jpg',
      desc: `Based on popular demand this is a dish of deep fried tofu served with homemade Burmese dipping sauce.`,
    },
    {
      id: 9,
      title: 'Somosa',
      category: 'entree',
      price: 5.99,
      img: './images/item-4.jpg',
      desc: `Deep fried parcel of soft potatoes, onion green peas seasoned with light curry and spices. Served with homemade dipping sauce 4 pcs per serving`,
       
    },
    {
      id: 10,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 11,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 12,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 13,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 14,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 15,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 16,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 17,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 18,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    {
      id: 19,
      title: 'Buu Tee Kyaw(aka) Deep fried Courd',
      category: 'entree',
      price: 8.99,
      img: './images/item-5.jpg',
      desc: `Fresh gourd dipped in our unique batter and fried to perfection! served with our homemade sauce `,
    },
    
  ];
  export default menu;